version: '3'

services:
  calculadora_rest: # el nombre del Proyecto en application.properties
    build: CalculadoraRest # busca carpeta donde esta el archivo "Dockerfile" dentro del proyecto para construir la imagen
    mem_limit: 512m # memoria asignada
    ports:
      - "8080:8080"
#   environment:
#     DB_URL: jdbc:mysql://calculadora:3306/calculadoraBD?createDatabaseIfNotExist=true&serverTimezone=UTC
#     DB_USER_NAME: root
#     DB_PASSWORD: 1234
#    restar: always # se reinicia si es necesario la conexion a la BD
#    depends_on: # depende de la variable "calculadora" declara en la linea 17 con sus atributos
#      calculadora:
#        condition: service_healty
#  calculadora:
#    image: mysql:8.0.33 # Aqui la misma version del JDBC de la BD que se encuentra en el POM del proyecto
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_PASSWORD: 1234
#      MYSQL_DATABASE: calculadoraBD
#    restart: always
#    healtcheck: # datos especificos de la salud de la BD y su conexion
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 10s
#      retries: 10